apiVersion: v1
kind: Service
metadata:
  name: nextjs-dashboard
  labels:
    app: nextjs-dashboard
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 32000
  selector:
    app: nextjs-dashboard
